version: '3.8'

services:
  ical-api:
    build: .
    container_name: ical-to-json-api
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET:-default-development-secret}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s