name: Trigger auto deployment for ical-json-converter

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ical-json-converter-AutoDeployTrigger-76143fb9-dc9e-43fa-a73d-586b2e92bcd0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ICALJSONCONVERTER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ICALJSONCONVERTER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ICALJSONCONVERTER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: icaljson-ccb2c8czafawcua4.azurecr.io
          registryUsername: ${{ secrets.ICALJSONCONVERTER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ICALJSONCONVERTER_REGISTRY_PASSWORD }}
          containerAppName: ical-json-converter
          resourceGroup: GlideTrips
          imageToBuild: icaljson-ccb2c8czafawcua4.azurecr.io/ical-json-converter:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


